#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-merge-commit hook"

DEPLOY_BRANCH=(npx git-branch-is -r "^(main|dev)$")

if [ $DEPLOY_BRANCH == '' ]; then
  yarn build
  cp ./build/cli.js dist/cli.js
  git add dist/cli.js
  git commit --amend
  git push
  exit 0
fi
