#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-merge-commit hook"

# check if is main branch
DEPLOY_BRANCH=(npx git-branch-is -r "^(main|dev)$")

if [ $DEPLOY_BRANCH == '' ]; then
  echo "Prepare build"
  yarn build

  echo "Move build to dist"
  cp ./build/cli.js dist/cli.js

  echo "Commit changes"
  git add dist/cli.js
  git commit --amend
  git push
  exit 0
fi
