#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-commit hook"

git checkout HEAD -- ./dist/cli.js

npx lint-staged

# check if is main branch
DEPLOY_BRANCH=(npx git-branch-is -r "^(main|dev)$")

if [ $DEPLOY_BRANCH != 1 ]; then
  echo "Prepare build"
  yarn build

  echo "Move build to dist"
  cp ./build/cli.js dist/cli.js

  echo "Commit changes"
  git add dist/cli.js

  exit 0
fi
